/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ElectionRegistry {
  export type VoteRecordStruct = {
    nullifier: BytesLike;
    voteHash: BytesLike;
    timestamp: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type VoteRecordStructOutput = [
    nullifier: string,
    voteHash: string,
    timestamp: bigint,
    blockNumber: bigint
  ] & {
    nullifier: string;
    voteHash: string;
    timestamp: bigint;
    blockNumber: bigint;
  };
}

export interface ElectionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castVote"
      | "closeElection"
      | "createElection"
      | "electionCount"
      | "elections"
      | "getElection"
      | "getElectionCount"
      | "getTotalVotes"
      | "getVoteCount"
      | "getVoteHash"
      | "getVoteHistory"
      | "hasVoted"
      | "owner"
      | "setElectionStatus"
      | "voteHistory"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ElectionCreated"
      | "ElectionStatusChanged"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createElection",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "elections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElectionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteHash",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setElectionStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "voteHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elections", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setElectionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace ElectionCreatedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    name: string,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    name: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    name: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionStatusChangedEvent {
  export type InputTuple = [electionId: BigNumberish, active: boolean];
  export type OutputTuple = [electionId: bigint, active: boolean];
  export interface OutputObject {
    electionId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    nullifier: BytesLike,
    voteHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    nullifier: string,
    voteHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    nullifier: string;
    voteHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ElectionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ElectionRegistry;
  waitForDeployment(): Promise<this>;

  interface: ElectionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castVote: TypedContractMethod<
    [_electionId: BigNumberish, _nullifier: BytesLike, _voteHash: BytesLike],
    [void],
    "nonpayable"
  >;

  closeElection: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  createElection: TypedContractMethod<
    [_name: string, _startTime: BigNumberish, _endTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  electionCount: TypedContractMethod<[], [bigint], "view">;

  elections: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint] & {
        name: string;
        startTime: bigint;
        endTime: bigint;
        active: boolean;
        totalVotes: bigint;
      }
    ],
    "view"
  >;

  getElection: TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint] & {
        name: string;
        startTime: bigint;
        endTime: bigint;
        active: boolean;
        totalVotes: bigint;
      }
    ],
    "view"
  >;

  getElectionCount: TypedContractMethod<[], [bigint], "view">;

  getTotalVotes: TypedContractMethod<[_id: BigNumberish], [bigint], "view">;

  getVoteCount: TypedContractMethod<[_id: BigNumberish], [bigint], "view">;

  getVoteHash: TypedContractMethod<
    [_id: BigNumberish, _nullifier: BytesLike],
    [string],
    "view"
  >;

  getVoteHistory: TypedContractMethod<
    [_id: BigNumberish],
    [ElectionRegistry.VoteRecordStructOutput[]],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [_id: BigNumberish, _nullifier: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setElectionStatus: TypedContractMethod<
    [_id: BigNumberish, _active: boolean],
    [void],
    "nonpayable"
  >;

  voteHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        nullifier: string;
        voteHash: string;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _nullifier: BytesLike, _voteHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeElection"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createElection"
  ): TypedContractMethod<
    [_name: string, _startTime: BigNumberish, _endTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "electionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "elections"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint] & {
        name: string;
        startTime: bigint;
        endTime: bigint;
        active: boolean;
        totalVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElection"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint] & {
        name: string;
        startTime: bigint;
        endTime: bigint;
        active: boolean;
        totalVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElectionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalVotes"
  ): TypedContractMethod<[_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteCount"
  ): TypedContractMethod<[_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteHash"
  ): TypedContractMethod<
    [_id: BigNumberish, _nullifier: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoteHistory"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [ElectionRegistry.VoteRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [_id: BigNumberish, _nullifier: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setElectionStatus"
  ): TypedContractMethod<
    [_id: BigNumberish, _active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        nullifier: string;
        voteHash: string;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [string],
    "view"
  >;

  getEvent(
    key: "ElectionCreated"
  ): TypedContractEvent<
    ElectionCreatedEvent.InputTuple,
    ElectionCreatedEvent.OutputTuple,
    ElectionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionStatusChanged"
  ): TypedContractEvent<
    ElectionStatusChangedEvent.InputTuple,
    ElectionStatusChangedEvent.OutputTuple,
    ElectionStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ElectionCreated(uint256,string,uint256,uint256)": TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;
    ElectionCreated: TypedContractEvent<
      ElectionCreatedEvent.InputTuple,
      ElectionCreatedEvent.OutputTuple,
      ElectionCreatedEvent.OutputObject
    >;

    "ElectionStatusChanged(uint256,bool)": TypedContractEvent<
      ElectionStatusChangedEvent.InputTuple,
      ElectionStatusChangedEvent.OutputTuple,
      ElectionStatusChangedEvent.OutputObject
    >;
    ElectionStatusChanged: TypedContractEvent<
      ElectionStatusChangedEvent.InputTuple,
      ElectionStatusChangedEvent.OutputTuple,
      ElectionStatusChangedEvent.OutputObject
    >;

    "VoteCast(uint256,bytes32,bytes32,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
