/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ElectionRegistry } from "./ElectionRegistry";
export * as factories from "./factories";
export { ElectionRegistry__factory } from "./factories/ElectionRegistry__factory";
